version: '3.4'

services:
  backend:
    image: meu-backend:v1
    build:
      context: .
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD} .
    ports:
      - "8080:8080"
    depends_on:
      - db  
    networks:
      - minha-rede

  db:
    image: postgres:latest 
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5431:5432" 
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge
